CREATE TABLE STUDENTS (
    STUDENT_ID NUMBER(13,0), 
    PREFIX VARCHAR2(15), 
    FIRST_NAME VARCHAR2(30), 
    LAST_NAME VARCHAR2(50), 
    DOB DATE, 
    ADDRESS VARCHAR2(100), 
    DISTRICT VARCHAR2(50), 
    AMPHUR VARCHAR2(50), 
    PROVINCE VARCHAR2(50), 
    ZIPCODE VARCHAR2(10),
    EMAIL VARCHAR2(50),
    MOBILE VARCHAR2(15)
) ;

ALTER TABLE STUDENTS ADD PRIMARY KEY (STUDENT_ID) ENABLE;
ALTER TABLE STUDENTS MODIFY (LAST_NAME NOT NULL ENABLE);
ALTER TABLE STUDENTS MODIFY (FIRST_NAME NOT NULL ENABLE);